// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjhesoplmtgykjmlstib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqaGVzb3BsbXRneWtqbWxzdGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTY3MTMsImV4cCI6MjA2NTA5MjcxM30.TxSELQjJEAy4ld-V9pmkrQXob-rz6no17PWZS5NozcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);